config/routes.rb
Store::Application.routes.draw do
  get 'personal/:id', to: 'personal#show', as: 'personal_show'
  get 'personal/:id/orders', to: 'personal#orders', as: 'personal_orders'

  devise_for :users
  resources :line_items
  resources :carts
  resources :users

  get 'depot/index'
  get 'depot/search', to: 'depot#search', as: 'depot_search'
  get 'depot/:id', to: 'depot#show', as: 'depot_show'
  get 'payment', to: 'depot#payment', as: 'payment'
  resources :products

  root to: 'depot#index', as: 'depot'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product, params)
		quantity = params[:quantity].to_i || 1
		current_item = line_items.find_by(product_id: product.id)
		if current_item
			current_item.quantity += quantity
		else
			current_item = line_items.build(product_id: product.id)
			current_item.quantity = quantity
		end
		current_item
	end

	def total_price
		line_items.to_a.sum {|x| x.total_price}
	end

	def total_quantity
		line_items.sum :quantity
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to depot_url, notice: 'Ваша корзина пуста.' }
      format.js
      format.json { head :no_content }
    end
  end

  private
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to depot_url, notice: 'Invalid cart'
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_badge.html.erb
<% unless @cart.nil? || @cart.line_items.count.zero? %>
	<span class="new badge">
		<%= @cart.line_items.count.to_s %>
	</span>
<% end %>

app/views/carts/_cart.html.erb
<div id="cart" class="collection with-header">
  <h2 class="header-list-container header collection-header">Корзина</h2>
  <div class="collection-item">

    <table class="bordered collection <%= 'collection-unstyled' if cart.line_items.length.zero? %>">
    <% if cart.line_items.length.zero? %>
      <tr>
        <td>
          Ваша корзина пуста
        </td>
      </tr>
    </table>

    <br />
    <br />

    <div>
      <%= link_to 'В каталог', depot_path, class: "teal btn btn-large waves-effect waves-light" %>
    </div>
    
    <% else %>
      <thead>
        <tr>
          <th></th>
          <th data-field="title">Товарная позиция</th>
          <th data-field="quantity">Количество</th>
          <th data-field="price">Цена</th>
        </tr>
      </thead>

      <%= render cart.line_items %>

      <tr class="total_line">
        <td></td>
        <td></td>
        <td>Итог</td>
        <td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
      </tr>
    </table>

    <br />
    <br />

    <div class="actions">
      <%= link_to 'Оформить заказ', "#", class: "red btn btn-large waves-effect waves-light" %>
    </div>
    <% end %>
  </div>
</div>

<br />
<br />

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="container">
  <% breadcrumb :cart %>
	<p id="notice"><%= notice %></p>

	<%= render @cart %>
</div>