config/routes.rb
Store::Application.routes.draw do
  get 'personal/:id', to: 'personal#show', as: 'personal_show'
  get 'personal/:id/orders', to: 'personal#orders', as: 'personal_orders'

  devise_for :users
  resources :line_items
  resources :carts
  resources :users

  get 'depot/index'
  get 'depot/search', to: 'depot#search', as: 'depot_search'
  get 'depot/:id', to: 'depot#show', as: 'depot_show'
  get 'payment', to: 'depot#payment', as: 'payment'
  resources :products

  root to: 'depot#index', as: 'depot'

end

app/controllers/depot_controller.rb
class DepotController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def search
    if params[:search].present?
      @products = Product.search params[:search], misspellings: {edit_distance: 3, transpositions: true, partial: true}
    else
      @products = Product.order(:title).page(params[:page]).per(12)
    end
  end

  def index
    @products = Product.order(:title).page(params[:page]).per(12)
  end

  def show
  	@product = Product.find(params[:id])
  end

  def payment
  end
end

app/helpers/depot_helper.rb
module DepotHelper
end

app/views/depot/_header.html.erb
<header>
  <%= render "navbar" %>
  <%= render "sidenav" %>
</header>

app/views/depot/_modal.html.erb
<div id="modal-decide-view" class="modal">
  <div class="modal-header" style="margin-top: 5px;">
    <a href="#!" class="right modal-action modal-close waves-effect waves-green btn-flat">
      <i class="fa fa-times"></i>
    </a>
  </div>
  <div class="modal-content">
    <h4 class="header center-align">Товар добавлен в корзину!</h4>

    <br />

    <div class="container" style="margin-top: 20px;">
      <div class="row">
        <div class="col l6 m6">
          <div class="col l12 m12">
            <% unless @product.image_url.empty? %>
              <%= image_tag(@product.image_url.to_s, height: 200, class: "cart-image") %>
            <% end %>
          </div>
        </div>
        <div class="col l6 m6">
          <div style="padding: 0.5rem;">
            <ul>
              <li>
                <h5 class="truncate">
                  <%= @product.title %>
                </h5>
                <% unless @product.article.to_s.empty? %>
                  <label>Артикул</label>
                  <h6>
                    <%= @product.article %>
                  </h6>
                <% end %>
              </li>
            </ul>

            <label>Цена:</label>

            <h5 class="price red-text" id="total_price"></h5>
          </div>
        </div>
      </div>
    </div>
      
    <div class="row">
      <%= link_to 'В каталог', depot_path, style: "margin-left: 4%;", class: "col m3 l3 btn btn-large waves-effect waves-light" %>
      <%= link_to 'Оформить заказ', '#', class: "col m3 l3 offset-l1 btn btn-large waves-effect waves-light" %>
      <%= link_to 'В корзину', @cart, class: "col m3 l3 offset-l1 btn btn-large waves-effect waves-light" %>
    </div>
  </div>
</div>

app/views/depot/_products.js.erb
<%= number_to_currency(@line_item.price, :precision => (@line_item.price.round == @line_item.price) ? 0 : 2) %>

app/views/depot/index.html.erb
<div class="container">
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
</div>

<div class="row">
  <% @products.each do |product| %>
    <div class="card-special col l4 s12 m6">
      <div class="card hoverable">
        <%= link_to depot_show_path(product) do %>
      <div class="card-image-special card-image waves-effect waves-block waves-light">
        <%= image_tag(product.image_url) %>
        <span class="card-title">
          <%= product.title %>
        </span>
      </div>
      <% end %>
      <div class="card-content">            
      <span class="card-title activator grey-text text-darken-4">
        <%= number_to_currency(product.price, :precision => (product.price.round == product.price) ? 0 : 2) %>
        <i class="mdi-navigation-more-vert right"></i>
      </span>
      </div>
      <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">
        <%= product.title %>
        <i class="mdi-navigation-close right"></i>
      </span>
      <blockquote>
        <p><%= sanitize(product.description) %></p>
      </blockquote>
      </div>
    </div>
    </div>
  <% end %>
</div>

<div id="paginator" class="center-paginator">
  <%= paginate @products %>
</div>

app/views/depot/payment.html.erb
<div class="container">
  <% breadcrumb :payment %>
  <p id="notice"><%= notice %></p>

  <div class="collection with-header">
    <h2 class="header-list-container header collection-header">Доставка</h2>
    <div class="collection-item">
      
    </div>
  </div>
</div>

app/views/depot/search.html.erb
<div class="container">
  <% breadcrumb :search, @products %>
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
</div>

<div class="row">
  <p class="flow-text container"><%= "По вашему запросу ничего не найдено" if @products.empty? %></p>
  <% @products.each do |product| %>
    <div class="card-special col l4 s12 m6">
      <div class="card hoverable">
        <%= link_to depot_show_path(product) do %>
      <div class="card-image-special card-image waves-effect waves-block waves-light">
        <%= image_tag(product.image_url) %>
        <span class="card-title">
          <%= product.title %>
        </span>
      </div>
      <% end %>
      <div class="card-content">            
      <span class="card-title activator grey-text text-darken-4">
        <%= number_to_currency(product.price, :precision => (product.price.round == product.price) ? 0 : 2) %>
        <i class="mdi-navigation-more-vert right"></i>
      </span>
      </div>
      <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">
        <%= product.title %>
        <i class="mdi-navigation-close right"></i>
      </span>
      <blockquote>
        <p><%= sanitize(product.description) %></p>
      </blockquote>
      </div>
    </div>
    </div>
  <% end %>
</div>

<div id="paginator" class="center-paginator">
  <%= paginate @products %>
</div>

app/views/depot/show.html.erb
<div class="container">
  <% breadcrumb :depot, @product %>
  <p id="notice"><%= notice %></p>

  <%= form_for(@product, method: :post, remote: true, url: line_items_path(product_id: @product)) do |f| %>

    <div class="row">
      <div class="col l8 m12 s12">
        <div class="col l12 m12">
          <ul>
            <li>
              <h4>
                <%= @product.title %>
              </h4>
              <p>Код товара для заказа по телефону: 
                <b>
                  <text class="red-text"><%= @product.article %></text>
                </b>
              </p>
            </li>
          </ul>
        </div>
        <div class="col l12 m12 s12">
          <%= image_tag(@product.image_url, class: "materialboxed", width: "400") %>
        </div>
      </div>
      <div class="col l4 m12 s12">
        <div class="card-panel white">
          <div style="padding: 0.5rem;">
            <label>Цена:</label>
            <h4 class="red-text card-price">
              <%= number_to_currency(@product.price, :precision => (@product.price.round == @product.price) ? 0 : 2) %>
            </h4>

            <label>Количество:</label>
            <%= number_field_tag :quantity, '1', min: 1,  placeholder: 1, required: 'required', class: 'form-control' %>

            <div class="center-align">
              <%= link_to 'Добавить в корзину', '#', class: "btn btn-large red waves-effect waves-light btn-submit modal-trigger", onclick: "$('#line_item_add').submit()" %>
            </div>

          </div>
        </div>
      </div>
    </div>
    <%= f.submit nil, id: "line_item_add", style: "display: none;" %>
  <% end %>

  <ul class="collection with-header">
    <li class="collection-header">
      <div class="section">
        <h5>Информация</h5>
      </div>
    </li>

    <li class="collection-item">
      <%= sanitize @product.description %>
    </li>
  </ul>
</div>

<%= render partial: 'modal' %>

<script type="text/javascript">
  $(document).on('ready page:load', function() {
    $('.modal-trigger').on('click', function(){
      $('#modal-decide-view').openModal();
    });
  });
</script>