config/routes.rb
Store::Application.routes.draw do
  get 'personal/:id', to: 'personal#show', as: 'personal_show'
  get 'personal/:id/orders', to: 'personal#orders', as: 'personal_orders'

  devise_for :users
  resources :line_items
  resources :carts
  resources :users

  get 'depot/index'
  get 'depot/search', to: 'depot#search', as: 'depot_search'
  get 'depot/:id', to: 'depot#show', as: 'depot_show'
  get 'payment', to: 'depot#payment', as: 'payment'
  resources :products

  root to: 'depot#index', as: 'depot'

end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">О компании</h5>
        <p class="grey-text text-lighten-4">Мы молодая, динамично развивающая компания...</p>


      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Settings</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
          <li><a class="white-text" href="#!">Link 3</a></li>
          <li><a class="white-text" href="#!">Link 4</a></li>
        </ul>
      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Connect</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
          <li><a class="white-text" href="#!">Link 3</a></li>
          <li><a class="white-text" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    Made by <a class="orange-text text-lighten-3" href="#">Materialize</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= render "layouts/navbar" %>

  <ul id="nav-mobile" class="side-nav fixed">
  	<%= render "layouts/sidenav" %>
  </ul>
</header>

app/views/layouts/_main.html.erb
<main>
  <div class="row">
    <% if params[:controller] == "personal" %>
      <%= render "personal/navbar" %>
    <% end %>
    
  	<div class="container" style="padding-top: 10px;">
  		<%= breadcrumbs separator: " &rsaquo; " %>
  	</div>

  	<%= yield %>

  </div>
  <a href="callto:+8003333733" class="btn-floating btn-large waves-effect waves-light right red call-button">
    <i class="mdi-communication-phone"></i>
  </a>
</main>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-tshop navbar-fixed megamenu" role="navigation">

  <div class="my-header">
    <nav class="nav-wrapper" style="height: 30px; line-height: 30px;">
      <div class="container">
        <div class="left side-nav-top">
          <ul class="userMenu">
            <li>
              <%= link_to payment_path, class: "waves-effect waves-light"  do %>
                <i class="mdi-action-info-outline hide-on-small-only left"></i>
                <span class="hide-on-small-only">Доставка</span>
                <i class="mdi-action-info-outline hide-on-med-and-up"></i>
              <% end %>
            </li>
            <li class="phone-number">
              <a href="callto:+8801680531352">
                <i class="hide-on-med-and-up mdi-notification-phone-in-talk"></i>
                <i class="hide-on-small-only mdi-notification-phone-in-talk left"></i>
                <span class="hide-on-small-only">+7 (911) 824 00 99</span>
              </a>
            </li>
          </ul>
        </div>
        <div class="right side-nav-top">
          <ul class="userMenu">
            <% if user_signed_in? %>
              <ul id="account" class="dropdown-content">
                <li>
                  <%= link_to "Мой кабинет", personal_orders_path(current_user) %>
                </li>
                <li class="divider"></li>
                <li><%= link_to "Выйти", destroy_user_session_path, :method => :delete %></li>
              </ul>

              <li>
                
                <a class="dropdown-button" href="#!" data-activates="account">Профиль
                  <i class="mdi-social-person left"></i>
                  <i class="material-icons right fa fa-chevron-down"></i>
                </a>
              </li>
              
            <% else %>
              <li>
                <a href="#" data-toggle="modal" data-target="#ModalLogin">
                  <i class="mdi-social-person hide-on-med-and-up"></i>
                  <span class="hide-on-small-only">
                    <%= link_to "Войти", new_user_session_path %>
                  </span>
                </a>
              </li>
              <li class="hide-on-small-only">
                <a href="#"  data-toggle="modal" data-target="#ModalSignup">
                  <%= link_to "Зарегистрироваться", new_user_registration_path %>
                </a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>

  <div class="navbar main-header">
    <nav class="nav-wrapper" style="height: 50px; line-height: 50px;">
      <div class="container">
        <ul class="left search-box" style="position: absolute;">
          <li>
            <a href="#" data-activates="mobile-demo" class="button-collapse">
              <i class="mdi-navigation-menu"></i>
            </a>
          </li>
          <li>
            <%= form_tag depot_search_path, method: :get, role: "search" do %>
              <div class="input-field">
                <%= text_field_tag :search, params[:search], autocomplete: "off", placeholder: " Поиск по сайту", class: "form-control" %>
                <!-- <input id="search" type="text" required placeholder=" Поиск по сайту"> -->
                <label for="search"><i class="mdi-action-search"></i></label>
                <%= submit_tag "Search", name: nil, style: "display: none;" %>
              </div>
            <% end %>
          </li>
        </ul>
        <ul id="nav-mobile" class="right">
          <li>
            <%= link_to @cart, class: "waves-effect waves-light tooltipped", data: { position: "bottom", delay: "50", tooltip: "В корзину" }, style: "height: 50px;"  do %>
              <i class="fa fa-shopping-cart"></i>
              <div id="cart-badge">
                <%= render partial: 'carts/badge', object: @cart %>
              </div>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
  </div>

  <ul class="side-nav fixed" id="mobile-demo">
    <%= render "layouts/sidenav" %>
  </ul>

</div>

<script type="text/javascript">
  $(".button-collapse").sideNav();
</script>

app/views/layouts/_sidenav.html.erb
<li class="logo">
  <%= link_to "WALLSSHOP", depot_path, id: "logo-container", class: "brand-logo" %>
</li>
<li class="bold"><a href="#">Подобрать обои</a></li>
<li class="no-padding">
  <ul class="collapsible collapsible-accordion">
    <li class="bold"><a class="collapsible-header active">Фабрики</a>
      <div class="collapsible-body">
        <ul>
          <li><a href="#">Фабрика №1</a></li>
          <!--li class="active"><a href="#">Фабрика №2</a></li-->
          <li><a href="#">Фабрика №2</a></li>
          <li><a href="#">Фабрика №3<span class="badge">10</span></a></li>
          <li><a href="#">Фабрика №4</a></li>
          <li><a href="#">Фабрика №5<span class="badge">400</span></a></li>
          <li><a href="#">Фабрика №6</a></li>
        </ul>
      </div>
    </li>
  </ul>
</li>
<li class="bold"><a href="#">Скидки!</a></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

  <%= render "layouts/header" %>
  <%= render "layouts/main" %>
  <%= render "layouts/footer" %>

</body>
</html>